import {
  ChartIcon,
  GiftIcon,
  ShieldIcon,
  UserIcon,
  UsersIcon,
  WalletIcon,
} from "@/common/icons";
import type { Capability } from "./coreCapabilities.types";

export const capabilities: Capability[] = [
  {
    id: "games-providers",
    connector: "M494 84 H560",
    detail: "(Endorphina, 77Gaming, Mascot, Zillion)",
    title: "Games Providers",
    meta: "4 direct integrations",
    href: "/platform/games-providers",
    side: "left",
    icon: <UserIcon />,
  },
  {
    id: "fiat-payments",
    connector: "M494 168 H560",
    detail: "(Endorphina, 77Gaming, Mascot, Zillion)",
    title: "Fiat Payments",
    meta: "30+ integrations",
    href: "/platform/fiat-payments",
    side: "left",
    icon: <WalletIcon />,
  },
  {
    id: "games-aggregators",
    connector: "M494 255 H560",
    detail: "(Endorphina, 77Gaming, Mascot, Zillion)",
    title: "Games Aggregators",
    meta: "4 integrations",
    href: "/platform/games-aggregators",
    side: "left",
    icon: <GiftIcon />,
  },
  {
    id: "crypto-payments",
    connector: "M636 80 H895",
    detail: "(Endorphina, 77Gaming, Mascot, Zillion)",
    title: "Crypto Payments",
    meta: "4 integrations",
    href: "/platform/crypto-payments",
    side: "right",
    icon: <ShieldIcon />,
  },
  {
    id: "marketing",
    connector: "M636 163 H895",
    detail: "(Endorphina, 77Gaming, Mascot, Zillion)",
    title: "Marketing",
    meta: "10+ integrations",
    href: "/platform/marketing",
    side: "right",
    icon: <UsersIcon />,
  },
  {
    id: "risk-management",
    connector: "M636 245 H895",
    detail: "(Endorphina, 77Gaming, Mascot, Zillion)",
    title: "Risk Management",
    meta: "3 integrations",
    href: "/platform/risk-management",
    side: "right",
    icon: <ChartIcon />,
  },
];
